### ISSUE TITLE
Artisanal + Flow Control for Bob's Logistics causes mod loading error on today's Artisanal release

### ISSUE THREAD

**Issue by AncalagonX** [oldskoolmatt/flow-control-expanded-bob#6]
I am using Flow Control for Bob's Logistics, Angel's + Bob's, and all the Artisanal reskins. As soon as I updated the Artisanal mods today in Factorio and restarted, it failed to load.

Please let me know if I can provide any better information. You can also ping me on Discord.

![image](https://user-images.githubusercontent.com/37827291/147939513-8d36adb5-009d-4882-a054-ae70d5322a44.png)

**Comment by AncalagonX** [comment]
It also throws an error for [Offshore P.U.M.P.S. and ground water](https://mods.factorio.com/mod/P-U-M-P-S).

![image](https://user-images.githubusercontent.com/37827291/147942424-8ee28b73-c7cc-4bc6-94fc-a642a2f32503.png)

**Comment by kirazy** [comment]
The specific change was that `base_entity` was renamed to `base_entity_name` for clarity as part of documentation improvements. Related: kirazy/reskins-library#4, and kirazy/reskins-library@4e2a4fabdf19a9ead3462b98be25222cdc29c02a.

**Comment by AncalagonX** [comment]
Thanks @oldskoolmatt ! You fixed that extremely rapidly. Thank you for your hard work. :)
